Added --verbose flag for "begin"
ideasman42/nerd-dictation pull request #85
Opened 2023-02-06 22:12 UTC by KJ7LNW

Moved suspend/resume notices to stderr and use --verbose flag

Added Model loading/loaded prints if --verbose is set.  This is useful for large datsets because it takes a while to load.  Then you can when it is ready to take dictation.

Signed-off-by: Eric Wheeler <vosk-git@z.ewheeler.org>

2023-02-06 22:27 UTC, ideasman42 commented
Thanks for the contribution, I'd prefer to make verbose an integer.

- `--verbose=0` (default) never print any text (Recording / Suspending / Resuming ... nothing).
- `--verbose=1` print "Model Loaded", "Recording starting" ... etc, the kinds of messages used for verbose in this PR.
- `--verbose=2` print additional information (useful for developers or anyone debugging nerd-dictation).

... 3 could be used to print noisy information each time a chunk of data that's handled - for e.g. but that could be added later.

2023-02-06 22:28 UTC, ideasman42 requested changes
Prefer --verbose is an integer so different levels can be set.

2023-02-07 00:22 UTC, KJ7LNW commented
> Prefer --verbose is an integer so different levels can be set.

 good idea. It is somehow inconsistent with the variable verbose that is passed to functions like main under suspend:

```py
def main_suspend(
    *,
    path_to_cookie: str = "",
    suspend: bool,
    verbose: bool,  # <<<<<
) -> None:
    import signal

    if not path_to_cookie:
        path_to_cookie = os.path.join(tempfile.gettempdir(), TEMP_COOKIE_NAME)

    if not os.path.exists(path_to_cookie):
        if verbose:
            sys.stderr.write("No running nerd-dictation cookie found at: {:s}, abort!\n".format(path_to_cookie))
```
should these be integers?

2023-02-07 02:13 UTC, ideasman42 commented
Verbose can be made into an integer everywhere.

2023-02-07 23:55 UTC, merged